
### owner creation
post http://localhost:4000/owner-api/owner
Content-Type: application/json

{
    "ownername":"ravi",
    "password":"ravi",
    "email":"ravi@mail.com"
}


#### owner login
post http://localhost:4000/owner-api/login
Content-Type: application/json

{
    "ownername":"ravi",
    "password":"ravi"
}
